name: prototype_ws_momoka
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  fluro: ^1.5.1
  auto_size_text: ^2.1.0 #untuk auto-size/responsive text
  cached_network_image: ^1.1.3
  url_launcher: ^4.2.0
  flutter_vlc_player: ^1.0.0
  web_socket_channel: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
  - assets/images/active_icon/account.png
  - assets/images/active_icon/games.png
  - assets/images/active_icon/home.png
  - assets/images/active_icon/leaderboard.png
  - assets/images/active_icon/reward.png
  - assets/images/non_active_icon/account.png
  - assets/images/non_active_icon/games.png
  - assets/images/non_active_icon/home.png
  - assets/images/non_active_icon/leaderboard.png
  - assets/images/non_active_icon/reward.png
  - assets/images/icon_appbar/bintang.png
  - assets/images/icon_appbar/coin.png
  - assets/images/icon_appbar/lonceng.png
  - assets/images/icon_appbar/ticket.png
  - assets/images/icons/ticket.png
  - assets/images/icons/pickup.png
  - assets/images/icons/reward_empty.png
  - assets/images/icons/coin_reward_image.jpg
  - assets/images/icons/coin_reward_detail.jpg
  - assets/images/icons/coin_reward_list.png
  - assets/images/icons/crab_sad_face.png
  - assets/images/icons/add_friend.png
  - assets/images/icons/background_prize_list.png

  - assets/images/icons/facebook.png
  - assets/images/icons/google.png
  - assets/images/icons/whatsapp.png

  - assets/images/contoh-hadiah.jpg
  
  # My Account Icon
  - assets/images/icons/myaccount_bg.png
  - assets/images/icons/menu_my_prizes_icon.png
  - assets/images/icons/menu_my_friend_icon.png
  - assets/images/icons/menu_my_address_icon.png
  - assets/images/icons/menu_my_orders_icon.png
  - assets/images/icons/menu_input_referral_icon.png
  - assets/images/icons/menu_gameplay_history_icon.png
  - assets/images/icons/menu_setting_icon.png
  - assets/images/icons/menu_info_icon.png
  - assets/images/icons/no-avatar.png
  - assets/images/icons/coin.png
  - assets/images/icons/ovo_icon.png
  - assets/images/icons/gopay_icon.png
  - assets/images/icons/coin_free.png
  - assets/images/icons/coin_history.png
  - assets/images/icons/reedem_voucher.png

  # Ticket
  - assets/images/icons/wave_bg_ticket.png
  - assets/images/icons/ticket_background.png
  - assets/images/icons/bg_my_coin.png

  # vangke nambah asset disini 
  - assets/images/login/login_bg.png
  - assets/images/login/facebook.png
  - assets/images/login/google.png
  - assets/images/momoka_logo.png
  - assets/images/loginbonus/
  - assets/images/screen_splashscreen.png
  - assets/images/text.png
  - assets/images/trophy.png
  - assets/images/coinhome.png
  - assets/images/newribbon.png
  - assets/images/saleribbon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
